config/routes.rb
Rails.application.routes.draw do
  resources :pay_slips
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/pay_slip.rb
class PaySlip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice)
        send_data pdf.render,
          filename: "Invoice #{@invoice.invoice_no}",
          type: "application/pdf",
          disposition: "inline"
    end
end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_no, :name, :payment_mode, :bank_detail)
    end
end

app/controllers/pay_slips_controller.rb
class PaySlipsController < ApplicationController
  before_action :set_pay_slip, only: [:show, :edit, :update, :destroy]

  # GET /pay_slips
  # GET /pay_slips.json
  def index
    @pay_slips = PaySlip.all
  end

  # GET /pay_slips/1
  # GET /pay_slips/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'show',
               layout: 'pdf.html'
      end
    end
  end

  # GET /pay_slips/new
  def new
    @pay_slip = PaySlip.new
  end

  # GET /pay_slips/1/edit
  def edit
  end

  # POST /pay_slips
  # POST /pay_slips.json
  def create
    @pay_slip = PaySlip.new(pay_slip_params)

    respond_to do |format|
      if @pay_slip.save
        format.html { redirect_to @pay_slip, notice: 'Pay slip was successfully created.' }
        format.json { render :show, status: :created, location: @pay_slip }
      else
        format.html { render :new }
        format.json { render json: @pay_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_slips/1
  # PATCH/PUT /pay_slips/1.json
  def update
    respond_to do |format|
      if @pay_slip.update(pay_slip_params)
        format.html { redirect_to @pay_slip, notice: 'Pay slip was successfully updated.' }
        format.json { render :show, status: :ok, location: @pay_slip }
      else
        format.html { render :edit }
        format.json { render json: @pay_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_slips/1
  # DELETE /pay_slips/1.json
  def destroy
    @pay_slip.destroy
    respond_to do |format|
      format.html { redirect_to pay_slips_url, notice: 'Pay slip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_slip
      @pay_slip = PaySlip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pay_slip_params
      params.require(:pay_slip).permit(:slip_no, :name, :income)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pay_slips_helper.rb
module PaySlipsHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :invoice_no %>
    <%= form.text_field :invoice_no, id: :invoice_invoice_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :invoice_name %>
  </div>

  <div class="field">
    <%= form.label :payment_mode %>
    <%= form.text_field :payment_mode, id: :invoice_payment_mode %>
  </div>

  <div class="field">
    <%= form.label :bank_detail %>
    <%= form.text_field :bank_detail, id: :invoice_bank_detail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice no</th>
      <th>Name</th>
      <th>Payment mode</th>
      <th>Bank detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_no %></td>
        <td><%= invoice.name %></td>
        <td><%= invoice.payment_mode %></td>
        <td><%= invoice.bank_detail %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %> |
<%= link_to 'Check out Pay Slips', pay_slips_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice no:</strong>
  <%= @invoice.invoice_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @invoice.name %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @invoice.payment_mode %>
</p>

<p>
  <strong>Bank detail:</strong>
  <%= @invoice.bank_detail %>
</p>

<%= link_to 'Generate PDF', invoice_path(@invoice, format: :pdf) %> |
<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrawnTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= stylesheet_link_tag wicked_pdf_asset_base64("pdf") %>
    <%= javascript_include_tag wicked_pdf_asset_base64("number_pages") %>

  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= image_tag wicked_pdf_asset_base64('logo.png') %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pay_slips/_form.html.erb
<%= form_with(model: pay_slip, local: true) do |form| %>
  <% if pay_slip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pay_slip.errors.count, "error") %> prohibited this pay_slip from being saved:</h2>

      <ul>
      <% pay_slip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :slip_no %>
    <%= form.text_field :slip_no, id: :pay_slip_slip_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pay_slip_name %>
  </div>

  <div class="field">
    <%= form.label :income %>
    <%= form.text_field :income, id: :pay_slip_income %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pay_slips/edit.html.erb
<h1>Editing Pay Slip</h1>

<%= render 'form', pay_slip: @pay_slip %>

<%= link_to 'Show', @pay_slip %> |
<%= link_to 'Back', pay_slips_path %>

app/views/pay_slips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pay Slips</h1>

<table>
  <thead>
    <tr>
      <th>Slip no</th>
      <th>Name</th>
      <th>Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pay_slips.each do |pay_slip| %>
      <tr>
        <td><%= pay_slip.slip_no %></td>
        <td><%= pay_slip.name %></td>
        <td><%= pay_slip.income %></td>
        <td><%= link_to 'Show', pay_slip %></td>
        <td><%= link_to 'Edit', edit_pay_slip_path(pay_slip) %></td>
        <td><%= link_to 'Destroy', pay_slip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pay Slip', new_pay_slip_path %>

app/views/pay_slips/new.html.erb
<h1>New Pay Slip</h1>

<%= render 'form', pay_slip: @pay_slip %>

<%= link_to 'Back', pay_slips_path %>

app/views/pay_slips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slip no:</strong>
  <%= @pay_slip.slip_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pay_slip.name %>
</p>

<p>
  <strong>Income:</strong>
  <%= @pay_slip.income %>
</p>

<%= link_to 'Generate PDF', pay_slip_path(@pay_slip, format: :pdf) %> |
<%= link_to 'Edit', edit_pay_slip_path(@pay_slip) %> |
<%= link_to 'Back', pay_slips_path %>

app/views/pay_slips/show.pdf.erb
hello